"""conversation_documents link table

Revision ID: d1c7bee6461b
Revises: 1329935b4330
Create Date: 2026-07-26 20:10:49.535673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c7bee6461b'
down_revision: Union[str, Sequence[str], None] = '1329935b4330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_documents',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'document_id')
    )
    # ### end Alembic commands ###

    # Backfill: seed each document's origin conversation as a context link.
    op.execute(
        "INSERT INTO conversation_documents (conversation_id, document_id) "
        "SELECT conversation_id, id FROM documents WHERE conversation_id IS NOT NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_documents')
    # ### end Alembic commands ###
